
---
version: "3.9"

services:
  samantha-backend:
    build:
      context: backend
    env_file: .env
    environment:
      PORT: "3000"
    ports:
      - '3000:3000'

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4040:4040