name: grafana

services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/monitor/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - multi-tenant

volumes:
  grafana_data:
    external: true
