name: Test agents-api
run-name: ${{ github.actor }} is testing the code

on:
  pull_request:
    paths:
      - 'agents-api/**'
  push:
    paths:
      - 'agents-api/**'

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install libboost
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libboost-all-dev
          version: 1.0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Set up python and install dependencies
        run: |
          cd agents-api
          uv python install
          uv sync --all-extras --dev

      - name: Run tests
        run: |
          cd agents-api
          uv run poe test --fail-limit 3

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
